### ISSUE TITLE
ImportError: No module named collections

### ISSUE THREAD

**Issue by inorton** [Marginal/EDMarketConnector#199]
Since modules.p was added I can no longer run the source build of EDMC, I suspect this is because my version of python is not 100% exactly the same as your one.  

I've found some background on this at http://stackoverflow.com/questions/24497214/python-cpickle-import-error

**Comment by inorton** [comment]
Aha! on closer inspection, it is trying to load "OrderedDict\r" from a module called "collections\r"

**Comment by inorton** [comment]
Turns out this is solved by doing `git config core.autocrlf true`

**Comment by JediRhymeTrix** [comment]
Is there any way of removing the unnecessary \r's from a .p file without git? I found one somewhere and am facing the same issue and was wondering how to solve it. Any help would be greatly appreciated.

**Comment by JediRhymeTrix** [comment]
@inorton Is there any way of removing the unnecessary \r's from a .p file without git? I found one somewhere and am facing the same issue and was wondering how to solve it. Any help would be greatly appreciated.

_Sent from my Galaxy Note8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Marginal** [comment]
@JediRhymeTrix 
Open the file in universal newlines mode for reading- `open('file.p', 'rU')`.
For writing it's best to open pickled files in binary mode to avoid this issue.

**Comment by JediRhymeTrix** [comment]
@Marginal I've tried rU but I'm still getting "no module named collections". Strangely, I only get this issue in Docker. It works fine on Windows 10 and Ubuntu even without rU.

_Sent from my Galaxy Note8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
